log = "mobile_config=debug,file_store=info,custom_tracing=info"
listen = "0.0.0.0:9081"
signing_keypair = "/opt/mobile-config/etc/keypair.bin"
admin_pubkey = "131kC5gTPFfTyzziHbh2PWz2VSdF4gDvhoC5vqCz25N7LFtDocF"

[database]
url = "postgres://postgres:postgres@postgres:5432/mobile_config"
max_connections = 10

[metadata]
url = "postgres://postgres:postgres@postgres:5432/mobile_metadata"
max_connections = 10

[metrics]
endpoint = "0.0.0.0:19000"
