[package]
name = "db-store"
version = "0.1.0"
description = "Database Store Library"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
metrics = {workspace = true }
poc-metrics = { path = "../metrics" }
thiserror = {workspace = true}
sqlx = {workspace = true}
serde = {workspace = true}
http = {workspace = true}
http-serde = {workspace = true}
tokio = {workspace = true}
triggered = {workspace = true}
futures = {workspace = true}

aws-config = "0"
aws-sdk-sts = "0"
aws-credential-types = "0"
aws-smithy-http = "0"
aws-types = "0"
aws-sig-auth = "0"

