[package]
name = "db-store"
version = "0.1.0"
description = "Database Store Library"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = {workspace = true}
sqlx = {workspace = true}
