# log settings for the application (RUST_LOG format). Default below
# 
# log = "poc-iot-verifier=debug,poc_store=info"


# Listen addres for public grpc. Default below
#
# listen = "0.0.0.0:8080"

[database]

# Url for database
url = "postgres://postgres:postgres@127.0.0.1:5432/index_db"

# Max connections to the database. Default below
#
# max_connections = 10

[metrics]

# Endpoint for metrics. Default below
#
# endpoint = "127.0.0.1:19000"
