# log settings for the application (RUST_LOG format). Default below
# 
# log = "iot-config=debug,poc_store=info"


# Listen addres for public grpc. Default below
#
# listen = "0.0.0.0:8080"

network = "mainnet"

[database]

# Postgres Connection Information
host = "127.0.0.1"
port = 5432
username = "postgres"
database = "config_db"
postgres_password = "postgres"

max_connections = 20

[helius]

# Url for the solana on-chain data such as hotspot asserted hexes
host = "helius.aws"
port = 5432
username = "helius"
database = "db"

auth_type = "iam"
# IAM Role to assume to generate db auth token

iam_role_arn = "arn::iam"
iam_role_session_name = "role-session-name"
iam_duration_seconds = 900
iam_region = "us-west-2"

# Max connections to database
max_connections = 20

[metrics]

# Endpoint for metrics. Default below
#
# endpoint = "127.0.0.1:19000"

[follower]

# Local grpc url to node follower for gateway location lookups
#[serde(with = "http_serde::uri", default = "default_url")]
# url = http://127.0.0.1:8080
# Start block to begin streaming followed transactions
block = 0
# Connect timeout for follower in seconds. Default 5
# connect = 5
# RPC timeout for follower in seconds. Default 5
# rpc = 5
# Batch size for gateway stream results. Default 100
# batch = 100
