[package]
name = "mobile-index"
version = "0.1.0"
description = "Reward Indexer for the Helium Mobile Network"
edition.workspace = true
authors.workspace = true
license.workspace = true


[dependencies]
config = {workspace = true}
clap = {workspace = true}
thiserror = {workspace = true}
serde =  {workspace = true}
serde_json = {workspace = true}
http-serde = {workspace = true}
sqlx = {workspace = true}
base64 = {workspace = true}
sha2 = {workspace = true}
lazy_static = {workspace = true}
triggered = {workspace = true}
futures = {workspace = true}
futures-util = {workspace = true}
prost = {workspace = true}
once_cell = {workspace = true}
file-store = {path = "../file_store"}
db-store = { path = "../db_store" }
poc-metrics = {path = "../metrics"}
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
metrics = {workspace = true }
metrics-exporter-prometheus = { workspace = true }
helium-proto = { workspace = true }
helium-crypto = { workspace = true }
rust_decimal = {workspace = true}
rust_decimal_macros = {workspace = true}
tonic = {workspace = true}
rand = "*"
async-trait = "*"

[package.metadata.deb]
depends = "$auto"
assets = [
    ["target/release/mobile-index", "/opt/mobile-index/bin/", "755"],
    ["pkg/deb/env-template", "/usr/share/mobile-index/env-template", "644"]
]
maintainer-scripts = "pkg/deb/"
systemd-units = { }
