log = "mobile_packet_verifier=debug,file_store=info,solana=info,custom_tracing=info"
cache = "/opt/mobile-packet-verifier/data"
enable_solana_integration = false

[database]
url = "postgres://postgres:postgres@postgres:5432/mobile_packet_verifier"
max_connections = 10

[ingest]
bucket = "mobile-ingest"
region = "us-east-1"
endpoint = "http://localstack:4566"

[output]
bucket = "mobile-packet-verifier"
region = "us-east-1"
endpoint = "http://localstack:4566"

[metrics]
endpoint = "0.0.0.0:19000"


[config_client]
url = "http://config:9081/"
signing_keypair = "/opt/mobile-packet-verifier/etc/keypair.bin"
config_pubkey = "14c5dZUZgFEVcocB3mfcjhXEVqDuafnpzghgyr2i422okXVByPr"
# /target/release/mobile-config-cli env info --keypair=docker/mobile/packet_verifier/keypair.bin
