
# log settings for the application (RUST_LOG format). Default below
# 
# log = "mobile-verifier=debug,poc_store=info"

# Cache location for generated verified reports; Required
cache = "/var/data/verfied-reports"

# Reward period in hours. (Default is 24)
# rewards = "24 hours"

# Verification offset in minutes, verification will occur at the end of
# the reward period + reward_offset; Default = 30 minutes
# reward_offset_minutes = "30 minutes"

[database]

# Postgres Connection Information
url = "postgres://postgres:postgres@127.0.0.1:5432/mobile_verifier"

# Max connections to the database.
max_connections = 50

[follower]

# Local grpc url to node follower for rewards tracking and submission
#[serde(with = "http_serde::uri", default = "default_url")]
# url = http://127.0.0.1:8080

# Start block to start streaming followed transactions from.
block = 0

# Connect timeout for follower in seconds. Default 5
# connect = 5

# RPC timeout for follower in seconds. Default 5
# rpc = 5

# batch size for gateway stream results. Default 100
# batch = 100

[ingest]

# Input bucket details for ingest data 

# Name of bucket to access ingest data. Required
#
bucket = "mainnet-mobile-ingest"

[promotion_ingest]

# Input bucket details for Service Provider Promotion Funds

# Name of bucket to access ingest data. Required
#
bucket = "price"

# Region for bucket. Defaults to below
#
# region = "us-west-2"

# Optional URL for AWS api endpoint. Inferred from aws config settings or aws
# IAM context by default
#
# endpoint = "https://aws-s3-bucket.aws.com"

[output]
# Output bucket for verified reports

# Name of bucket to write details to. Required
#
bucket = "mainnet-mobile-verified"

# Region for bucket. Defaults to below
#
# region = "us-west-2"

# Optional URL for AWS api endpoint. Inferred from aws config settings or aws
# IAM context by default
#
# endpoint = "https://aws-s3-bucket.aws.com"

[metrics]

# Endpoint for metrics. Default below
#
# endpoint = "127.0.0.1:19000"
