name: mobile
services:

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  localstack:
    image: localstack/localstack:stable
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
    ports:
      - 4566:4566
    volumes:
      - localstack-data:/var/lib/localstack
      - ./localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
  
  ingest:
    build:
      context: ../..
      dockerfile: ./Dockerfile
      args:
        - PACKAGE=ingest
    depends_on:
        localstack:
          condition: service_healthy
    stop_grace_period: 1s
    environment:
      - PACKAGE=ingest
    ports:
      - 9080:9080
    volumes:
      - ./settings/ingest.toml:/opt/ingest/etc/settings.toml

volumes:
  postgres-data:
  localstack-data: