
# log settings for the application (RUST_LOG format). Default below
# 
# log = "mobile_rewards=debug,poc_store=info"

#file to load keypair from
#
keypair = "/path/to/key_pair"

# Tigger interval in seconds. (Default is 900; 15 minutes)
#
# trigger = 900

# Rewards interval in seconds. (Default is 86400; 24 hours)
#
# rewards = 86400


[database]

# Url for database to write mobile rewards to
url = "postgres://postgres:postgres@127.0.0.1:5432/index_db"

# Max connections to the database. Default below
#
# max_connections = 10

[follower]

# Local grpc url to node follower for rewards tracking and submission
#[serde(with = "http_serde::uri", default = "default_url")]
# url = http://127.0.0.1:8080

# Start block to start streaming followed transactions from.
block = 0

# Connect timeout for follower in seconds. Default 5
# connect = 5

# RPC timeout for follower in seconds. Default 5
# rpc = 5

# batch size for gateway stream results. Default 100
# batch = 100

[transactions]

# Local grpc url to node follower for rewards tracking and submission
#[serde(with = "http_serde::uri", default = "default_url")]
# url = http://127.0.0.1:8080

# Start block to start streaming followed transactions from.
block = 0

# Connect timeout for follower in seconds. Default 5
# connect = 5

# RPC timeout for follower in seconds. Default 5
# rpc = 5

# batch size for gateway stream results. Default 100
# batch = 100

[verifier]

# Input bucket details for verified reports

# Name of bucket to access verified data. Required
#
bucket = "mainnet-verified-bucket"

# Region for bucket. Defaults to below
#
# region = "us-west-2"

# Optional URL for AWS api endpoint. Inferred from aws config settings or aws
# IAM context by default
#
# endpoint = "https://aws-s3-bucket.aws.com"

[output]
# Output bucket for reward reports

# Name of bucket to write details to. Required
#
bucket = "mainnet-rewards-bucket"

# Region for bucket. Defaults to below
#
# region = "us-west-2"

# Optional URL for AWS api endpoint. Inferred from aws config settings or aws
# IAM context by default
#
# endpoint = "https://aws-s3-bucket.aws.com"

[metrics]

# Endpoint for metrics. Default below
#
# endpoint = "127.0.0.1:19000"





