[package]
name = "price"
version = "0.1.0"
description = "Price Oracle for the Helium Network"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
config = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
chrono = { workspace = true }
helium-proto = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
triggered = { workspace = true }
humantime-serde = { workspace = true }

custom-tracing = { path = "../custom_tracing" }
file-store = { path = "../file_store" }
file-store-oracles = { path = "../file_store_oracles" }
poc-metrics = { path = "../metrics" }
solana = { path = "../solana" }
task-manager = { path = "../task_manager" }
tls-init = { path = "../tls_init" }

[dev-dependencies]
temp-env = "0.3.6"
