[package]
name = "mobile-packet-verifier"
version = "0.1.0"
description = "Packet verification for Mobile"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
helium-crypto = { workspace = true, features = [
    "sqlx-postgres",
    "multisig",
    "solana",
] }
helium-proto = { workspace = true }
http = { workspace = true }
http-serde = { workspace = true }
humantime-serde = { workspace = true }
metrics = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
solana = { path = "../solana" }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
triggered = { workspace = true }

custom-tracing = { path = "../custom_tracing" }
db-store = { path = "../db_store" }
file-store = { path = "../file_store" }
mobile-config = { path = "../mobile_config" }
poc-metrics = { path = "../metrics" }
task-manager = { path = "../task_manager" }
tls-init = { path = "../tls_init" }

[dev-dependencies]
reqwest = { workspace = true }
