#! /bin/bash

init() {
    local -r pg_user='postgres'
    local -r pg_db_names=(
        'test_mobile_rewards'
        'test_mobile_verifier'
    )
    local -r pg_container_id=$(docker ps --filter=name=postgres --format='{{.ID}}')

    docker exec -it "$pg_container_id" apt update
    docker exec -it "$pg_container_id" apt install sudo

    local db
    for db in "${pg_db_names[@]}"; do
        docker exec -it "$pg_container_id" sudo -u "$pg_user" createdb "$db"
    done
}

case "$1" in
    start)
        # XXX Assumes the following variables are already set:
        # - AWS_ACCESS_KEY_ID
        # - AWS_SECRET_ACCESS_KEY
        . infra.sh
        infra-start;;
    stop)
        . infra.sh
        infra-stop drop;;
    init)
        init;;
    *)
        printf 'usage: %s (start|stop)\n' "$0" >&2
        exit 1
esac
