# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='heartbeat.proto',
  package='helium.poc_mobile',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fheartbeat.proto\x12\x11helium.poc_mobile\"\x98\x01\n\x10speedtest_req_v1\x12\x0f\n\x07pub_key\x18\x01 \x01(\x0c\x12\x0e\n\x06serial\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x14\n\x0cupload_speed\x18\x04 \x01(\x04\x12\x16\n\x0e\x64ownload_speed\x18\x05 \x01(\x04\x12\x0f\n\x07latency\x18\x06 \x01(\r\x12\x11\n\tsignature\x18\x07 \x01(\x0c\"\x1f\n\x11speedtest_resp_v1\x12\n\n\x02id\x18\x01 \x01(\t\"\xcf\x01\n\x15\x63\x65ll_heartbeat_req_v1\x12\x0f\n\x07pub_key\x18\x01 \x01(\x0c\x12\x14\n\x0chotspot_type\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x65ll_id\x18\x03 \x01(\r\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x0b\n\x03lat\x18\x05 \x01(\x01\x12\x0b\n\x03lon\x18\x06 \x01(\x01\x12\x16\n\x0eoperation_mode\x18\x07 \x01(\x08\x12\x15\n\rcbsd_category\x18\x08 \x01(\t\x12\x0f\n\x07\x63\x62sd_id\x18\t \x01(\t\x12\x11\n\tsignature\x18\n \x01(\x0c\"$\n\x16\x63\x65ll_heartbeat_resp_v1\x12\n\n\x02id\x18\x01 \x01(\t2\xd9\x01\n\npoc_mobile\x12]\n\x10submit_speedtest\x12#.helium.poc_mobile.speedtest_req_v1\x1a$.helium.poc_mobile.speedtest_resp_v1\x12l\n\x15submit_cell_heartbeat\x12(.helium.poc_mobile.cell_heartbeat_req_v1\x1a).helium.poc_mobile.cell_heartbeat_resp_v1b\x06proto3'
)




_SPEEDTEST_REQ_V1 = _descriptor.Descriptor(
  name='speedtest_req_v1',
  full_name='helium.poc_mobile.speedtest_req_v1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='helium.poc_mobile.speedtest_req_v1.pub_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial', full_name='helium.poc_mobile.speedtest_req_v1.serial', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='helium.poc_mobile.speedtest_req_v1.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upload_speed', full_name='helium.poc_mobile.speedtest_req_v1.upload_speed', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_speed', full_name='helium.poc_mobile.speedtest_req_v1.download_speed', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latency', full_name='helium.poc_mobile.speedtest_req_v1.latency', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='helium.poc_mobile.speedtest_req_v1.signature', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=191,
)


_SPEEDTEST_RESP_V1 = _descriptor.Descriptor(
  name='speedtest_resp_v1',
  full_name='helium.poc_mobile.speedtest_resp_v1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helium.poc_mobile.speedtest_resp_v1.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=224,
)


_CELL_HEARTBEAT_REQ_V1 = _descriptor.Descriptor(
  name='cell_heartbeat_req_v1',
  full_name='helium.poc_mobile.cell_heartbeat_req_v1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='helium.poc_mobile.cell_heartbeat_req_v1.pub_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotspot_type', full_name='helium.poc_mobile.cell_heartbeat_req_v1.hotspot_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_id', full_name='helium.poc_mobile.cell_heartbeat_req_v1.cell_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='helium.poc_mobile.cell_heartbeat_req_v1.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat', full_name='helium.poc_mobile.cell_heartbeat_req_v1.lat', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lon', full_name='helium.poc_mobile.cell_heartbeat_req_v1.lon', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_mode', full_name='helium.poc_mobile.cell_heartbeat_req_v1.operation_mode', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cbsd_category', full_name='helium.poc_mobile.cell_heartbeat_req_v1.cbsd_category', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cbsd_id', full_name='helium.poc_mobile.cell_heartbeat_req_v1.cbsd_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='helium.poc_mobile.cell_heartbeat_req_v1.signature', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=434,
)


_CELL_HEARTBEAT_RESP_V1 = _descriptor.Descriptor(
  name='cell_heartbeat_resp_v1',
  full_name='helium.poc_mobile.cell_heartbeat_resp_v1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helium.poc_mobile.cell_heartbeat_resp_v1.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=472,
)

DESCRIPTOR.message_types_by_name['speedtest_req_v1'] = _SPEEDTEST_REQ_V1
DESCRIPTOR.message_types_by_name['speedtest_resp_v1'] = _SPEEDTEST_RESP_V1
DESCRIPTOR.message_types_by_name['cell_heartbeat_req_v1'] = _CELL_HEARTBEAT_REQ_V1
DESCRIPTOR.message_types_by_name['cell_heartbeat_resp_v1'] = _CELL_HEARTBEAT_RESP_V1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

speedtest_req_v1 = _reflection.GeneratedProtocolMessageType('speedtest_req_v1', (_message.Message,), {
  'DESCRIPTOR' : _SPEEDTEST_REQ_V1,
  '__module__' : 'heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:helium.poc_mobile.speedtest_req_v1)
  })
_sym_db.RegisterMessage(speedtest_req_v1)

speedtest_resp_v1 = _reflection.GeneratedProtocolMessageType('speedtest_resp_v1', (_message.Message,), {
  'DESCRIPTOR' : _SPEEDTEST_RESP_V1,
  '__module__' : 'heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:helium.poc_mobile.speedtest_resp_v1)
  })
_sym_db.RegisterMessage(speedtest_resp_v1)

cell_heartbeat_req_v1 = _reflection.GeneratedProtocolMessageType('cell_heartbeat_req_v1', (_message.Message,), {
  'DESCRIPTOR' : _CELL_HEARTBEAT_REQ_V1,
  '__module__' : 'heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:helium.poc_mobile.cell_heartbeat_req_v1)
  })
_sym_db.RegisterMessage(cell_heartbeat_req_v1)

cell_heartbeat_resp_v1 = _reflection.GeneratedProtocolMessageType('cell_heartbeat_resp_v1', (_message.Message,), {
  'DESCRIPTOR' : _CELL_HEARTBEAT_RESP_V1,
  '__module__' : 'heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:helium.poc_mobile.cell_heartbeat_resp_v1)
  })
_sym_db.RegisterMessage(cell_heartbeat_resp_v1)



_POC_MOBILE = _descriptor.ServiceDescriptor(
  name='poc_mobile',
  full_name='helium.poc_mobile.poc_mobile',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=475,
  serialized_end=692,
  methods=[
  _descriptor.MethodDescriptor(
    name='submit_speedtest',
    full_name='helium.poc_mobile.poc_mobile.submit_speedtest',
    index=0,
    containing_service=None,
    input_type=_SPEEDTEST_REQ_V1,
    output_type=_SPEEDTEST_RESP_V1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='submit_cell_heartbeat',
    full_name='helium.poc_mobile.poc_mobile.submit_cell_heartbeat',
    index=1,
    containing_service=None,
    input_type=_CELL_HEARTBEAT_REQ_V1,
    output_type=_CELL_HEARTBEAT_RESP_V1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POC_MOBILE)

DESCRIPTOR.services_by_name['poc_mobile'] = _POC_MOBILE

# @@protoc_insertion_point(module_scope)
