FROM apache/gravitino-iceberg-rest:1.0.0

WORKDIR /root/gravitino-iceberg-rest-server/libs


RUN curl -L -o postgresql-42.7.8.jar \
        https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.8/postgresql-42.7.8.jar