[package]
name = "coverage_point_calculator"
version = "0.1.0"
description = "Calculate Coverage Points for hotspots in the Mobile Network"
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
