[package]
name = "poc5g-rewards"
version = "0.1.0"
edition = "2021"
description = "Reward Server for the Helium Mobile Network"
authors = ["Marc Nijdam <marc@nova.xyz>"]
license = "Apache-2.0"


[dependencies]
dotenv = "0"
thiserror = "1"
serde =  {version = "1", features=["derive"]}
serde_json = "1"
clap = {version = "3", features = ["derive"]}
sqlx = {version = "0", features = ["postgres", "uuid", "decimal", "chrono", "migrate", "macros", "runtime-tokio-rustls"]}
tokio = { version = "1", default-features=false, features=["fs", "macros", "signal", "rt", "process", "time"] }
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
base64 = "0"
sha2 = "*"
lazy_static = "*"
chrono = {version = "0", features = ["serde"]}
triggered = "0"
futures = "*"
futures-util = "*"
prost = "*"
once_cell = "1"
poc-store = {path = "../store"}
helium-proto = {git = "https://github.com/helium/proto", branch = "master", features = ["services"]}
helium-crypto = {git = "https://github.com/helium/helium-crypto-rs", tag="v0.3.4"}
rust_decimal = "1"
rust_decimal_macros = "1"
tonic = "0"
http = "*"
prettytable-rs = "*"
rand = "*"
