[package]
name = "custom-tracing"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "6"
anyhow = "1"
futures = "0"
tokio = { version = "1", features = ["rt-multi-thread", "signal"] }
tracing = "0"
tracing-subscriber = { version = "0", default-features = true, features = [
    "env-filter",
    "registry",
    "fmt",
] }
tower-http = { version = "0", features = ["trace"] }
tower-layer = "0"
axum = "0"
