[package]
name = "test-mobile"
version = "0.1.0"
description = "Test Mobile Stack"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-compression = { version = "0", features = ["tokio", "gzip"] }
clap = { workspace = true }
custom-tracing = { path = "../custom_tracing" }
file-store = { path = "../file_store" }
h3o = { workspace = true, features = ["geo"] }
helium-proto = { workspace = true }
hextree = { workspace = true }
tokio = { workspace = true, features = ["io-util", "fs"] }
triggered = { workspace = true }

[dev-dependencies]
backon = "0"
bs58 = { workspace = true }
custom-tracing = { path = "../custom_tracing" }
chrono = { workspace = true }
helium-crypto = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
