[package]
name = "test-mobile"
version = "0.1.0"
description = "Test All"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
helium-crypto = { workspace = true }
