[package]
name = "test-mobile"
version = "0.1.0"
description = "Test Mobile Stack"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["io-util", "fs"] }
clap = { workspace = true }
hextree = { workspace = true }
flate2 = "1"
async-compression = { version = "0", features = ["tokio", "gzip"] }
