# RUST_LOG compatible settings string
#
log = "promotion_fund=info"

# Destination of file to be watched for dynamically updating log level.
# Write a RUST_LOG compatible string to see new logs.
#
# custom_tracing = "./tracing.cfg"

# Temporary storage for Service Provider Promotion Funds before uploading to S3
#
file_sink_cache = "/tmp/oracles/promotion-fund"

# How often to check with Solana for updates to Service Provider Funds
#
solana_check_interval = "6 hours"

[solana]
# Solana RPC. This may contain a secret
#
rpc_url = "https://api.devnet.solana.com"

# Public key for the DNT Mint (Mobile mint)
#
dnt_mint = "mb1eu7TzEc71KxDpsmsKoucSSuuoGLv1drys1oP2jh6"

[file_store_output]
# Output bucket name for Service Provider Promotion Funds
#
bucket = "service-provider-promotions"

# Region for bucket. Defaults to below
#
# region = "us-west-2"

# Optional URL for AWS api endpoint. Inferred from aws config settings or aws
# IAM context by default
#
# endpoint = "https://aws-s3-bucket.aws.com"

# Access Key when using S3 locally
#
# access_key_id = ""

# Secret Key when using S3 locally
#
# secret_access_key = ""

[metrics]
# Prometheus endpoint
#
# endpoint = "127.0.0.1:19001"
