use super::plan::Plan;
use super::Cmd;
use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

/// Default local docker-compose settings written to disk on first run. Mirrors
/// what `[trino]` and `[database]` need for the compare-trino subcommands to
/// talk to the local stack.
const LOCAL_SETTINGS: &str = r#"# Auto-generated by `mobile-verifier-compare seed`.
# Safe to edit — re-running seed will not overwrite this file.

log = "mobile_verifier_compare=info"

[database]
url = "postgres://postgres:postgres@127.0.0.1:5432/mobile_verifier"
max_connections = 10

[trino]
host = "127.0.0.1"
port = 8080
user = "admin"
secure = false
catalog = "iceberg"
"#;

const LOCAL_SETTINGS_PATH_FROM_CRATE: &str = "pkg/compare-trino-settings.local.toml";

pub fn print(plan: &Plan, args: &Cmd) -> Result<()> {
    let settings_path = write_local_settings_if_missing()?;
    let start = plan.epoch_start.to_rfc3339();
    let end = plan.epoch_end.to_rfc3339();
    let mpv_url = &args.mpv_database_url;

    println!();
    println!("✔ seeded {} hotspots across 4 buckets", plan.hotspots.len());
    println!("  window: {start} → {end}");
    println!();
    println!("next steps:");
    println!(
        "  # settings file (auto-written if missing): {}",
        settings_path.display()
    );
    println!("  cargo run -p mobile-verifier-compare -- \\");
    println!("    -c {} \\", settings_path.display());
    println!("    all --start {start} --end {end} \\");
    println!("    --mpv-database-url '{mpv_url}'");
    println!();
    println!("  # add --show-all to any subcommand to see MATCH rows too");
    Ok(())
}

/// Write `mobile_verifier_compare/pkg/compare-trino-settings.local.toml` if it doesn't
/// already exist, and return its path (relative to the workspace root if
/// possible, otherwise absolute) for display in the next-steps blurb.
fn write_local_settings_if_missing() -> Result<PathBuf> {
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let abs = crate_root.join(LOCAL_SETTINGS_PATH_FROM_CRATE);
    if !abs.exists() {
        if let Some(parent) = abs.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating settings parent dir {}", parent.display()))?;
        }
        fs::write(&abs, LOCAL_SETTINGS).with_context(|| format!("writing {}", abs.display()))?;
        println!("[settings] wrote {}", abs.display());
    } else {
        println!("[settings] {} already exists, leaving as-is", abs.display());
    }
    // Try to render relative to the cwd to keep the printed command short.
    if let Ok(cwd) = std::env::current_dir() {
        if let Ok(rel) = abs.strip_prefix(&cwd) {
            return Ok(rel.to_path_buf());
        }
    }
    Ok(abs)
}
