# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lora_pb2 as lora__pb2


class poc_loraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.submit_lora_beacon = channel.unary_unary(
                '/helium.poc_lora.poc_lora/submit_lora_beacon',
                request_serializer=lora__pb2.lora_beacon_report_req_v1.SerializeToString,
                response_deserializer=lora__pb2.lora_beacon_report_resp_v1.FromString,
                )
        self.submit_lora_witness = channel.unary_unary(
                '/helium.poc_lora.poc_lora/submit_lora_witness',
                request_serializer=lora__pb2.lora_witness_report_req_v1.SerializeToString,
                response_deserializer=lora__pb2.lora_witness_report_resp_v1.FromString,
                )


class poc_loraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def submit_lora_beacon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_lora_witness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_poc_loraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'submit_lora_beacon': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_lora_beacon,
                    request_deserializer=lora__pb2.lora_beacon_report_req_v1.FromString,
                    response_serializer=lora__pb2.lora_beacon_report_resp_v1.SerializeToString,
            ),
            'submit_lora_witness': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_lora_witness,
                    request_deserializer=lora__pb2.lora_witness_report_req_v1.FromString,
                    response_serializer=lora__pb2.lora_witness_report_resp_v1.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helium.poc_lora.poc_lora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class poc_lora(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def submit_lora_beacon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helium.poc_lora.poc_lora/submit_lora_beacon',
            lora__pb2.lora_beacon_report_req_v1.SerializeToString,
            lora__pb2.lora_beacon_report_resp_v1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def submit_lora_witness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helium.poc_lora.poc_lora/submit_lora_witness',
            lora__pb2.lora_witness_report_req_v1.SerializeToString,
            lora__pb2.lora_witness_report_resp_v1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
