name: DockerPackage

on:
  workflow_run:
    workflows: ["Docker CI"]  # Run only if "Docker CI" workflow succeeds
    types:
      - completed
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version (e.g., 1.0.0)"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # package: [boost-manager, ingest, iot-config, iot-packet-verifier, iot-verifier, mobile-config, mobile-packet-verifier, mobile-verifier, poc-entropy, price, reward-index]
        package: [ingest]
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-build-${{ matrix.package }}
      cancel-in-progress: true
    if: > 
      github.event_name == 'workflow_dispatch' && github.event.inputs.release_version != '' && github.event.inputs.release_version != null ||
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'refs/tags/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN  }}
          role-session-name: gha_build_${{ github.repository_id }}_${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Determine Release Version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.release_version }}" ]]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            TAG_NAME="${{ github.event.workflow_run.head_branch }}"
            TAG_NAME=${TAG_NAME#refs/tags/}
            echo "RELEASE_VERSION=$TAG_NAME" >> $GITHUB_ENV
          fi

      - name: Set ECR URL
        run: |
          case "${{ matrix.package }}" in
            ingest)
              echo "ECR_URL=${{ vars.INGEST_ECR_URL }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unsupported package: ${{ matrix.package }}"
              exit 1
              ;;
          esac
      - name: Build the Docker image
        run: |
          echo "Building Docker image with RELEASE_VERSION=${{ env.RELEASE_VERSION }}"
          docker build  --target runner --build-arg PACKAGE=${{ matrix.package }} -t ${{ env.ECR_URL }}:${{ env.RELEASE_VERSION }} -f Dockerfile .
      - name: Push Docker image to ECR
        run: |
          echo "Pushing image ${{ env.RELEASE_VERSION }} to ${{ env.ECR_URL }}"
          docker push ${{ env.ECR_URL }}:${{ env.RELEASE_VERSION }}
