name: Package

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]

env:
  CARGO_INCREMENTAL: 0 # this setting is automatically applied by rust-cache but documented here for explicitness
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  on-failure:
    runs-on: oracles-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  on-success:
    runs-on: oracles-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-release
      cancel-in-progress: true
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} && contains(github.ref, 'refs/tags/')
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Release
        run: cargo build --all --release

      - name: Debian packaging
        env:
          # PACKAGECLOUD_API_KEY: ${{ secrets.PACKAGECLOUD_API_KEY }}
          PACKAGECLOUD_API_KEY: XXX
        run: |
          chmod +x ./.github/scripts/make_debian.sh
          ./.github/scripts/make_debian.sh
