name: Release

on:
  workflow_dispatch:  # Allows manual triggering for testing
    inputs:
      release_version:
        description: "Release Version (e.g., 1.0.0)"
        required: true
        type: string

env:
  CARGO_INCREMENTAL: 0 # this setting is automatically applied by rust-cache but documented here for explicitness
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-release
      cancel-in-progress: true
    if: contains(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Show Inputs
        run: |
          echo "Release Version: ${{ github.event.inputs.release_version }}"

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y curl unzip build-essential

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release
        run: cargo build --all --release

      - name: Debian packaging
        env:
          PACKAGECLOUD_API_KEY: ${{ secrets.PACKAGECLOUD_API_KEY }}
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
        run: |
          chmod +x ./.github/scripts/make_debian.sh
          ./.github/scripts/make_debian.sh
