name: Release

on:
  workflow_run:
    workflows: ["CI"]  # Triggers after CI workflow completes
    types:
      - completed
  workflow_dispatch:  # Allows manual triggering
    inputs:
      release_version:
        description: "Release Version (e.g., 1.0.0)"
        required: true
        type: string

env:
  CARGO_INCREMENTAL: 0 # this setting is automatically applied by rust-cache but documented here for explicitness
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-release
      cancel-in-progress: true
    if: > 
      (github.event_name == 'workflow_dispatch') || 
      (github.event.workflow_run.conclusion == 'success' && contains(github.ref, 'refs/tags/'))
    steps:
      - name: Free Up Disk Space
        run: |
          echo "Freeing up disk space..."
          echo "Disk space before cleanup:"
          df -h
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android /usr/lib/jvm /usr/local/share/boost /opt/hostedtoolcache
          docker system prune -a -f
          echo "Disk space after cleanup:"
          df -h

      - name: Show Inputs
        run: |
          echo "Release Version: ${{ github.event.inputs.release_version }}"

      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y tzdata
          ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata
          apt-get install -y curl build-essential pkg-config libssl-dev unzip

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # TODO: update key when we retire 20.04
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-20.04-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Release
        run: cargo build --all --release

      - name: Debian packaging
        env:
          PACKAGECLOUD_API_KEY: ${{ secrets.PACKAGECLOUD_API_KEY }}
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
        run: |
          chmod +x ./.github/scripts/make_debian.sh
          ./.github/scripts/make_debian.sh
